name: securepass
description: Read passports using nfc


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  camera: ^0.9.8+1
  google_ml_kit: ^0.11.0
  intl: ^0.17.0
  get: ^4.6.5
  shared_preferences: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


  assets:
   - assets/images/


  module:
    androidX: true
    androidPackage: com.securepass.securepass.securepass
    iosBundleIdentifier: com.securepass.securepass.securepass
